import "./globals.css";
import Head from "next/head";
import Providers from "./providers";
import { Roboto } from "@next/font/google";
import Navbar from "src/components/modules/navbar";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  variable: "--roboto-font",
});

export default function RootLayout({ children }: { children: JSX.Element }) {
  return (
    <html lang="en" className={roboto.variable}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Providers>
          <Navbar />
          {/*<PageContainer>{children}</PageContainer>*/}
          {children}
        </Providers>
      </body>
    </html>
  );
}
