import "./globals.css";
import Head from "next/head";
import Providers from "./providers";
import {Roboto} from "@next/font/google";
import Navbar from "src/components/modules/navbar";
import Footer from "src/components/modules/Footer";

const roboto = Roboto({
    weight: ["400", "500", "700"],
    variable: "--roboto-font",
});

type RootLayoutPropsType = {
    children?: JSX.Element;
};
export default function RootLayout({children}: RootLayoutPropsType) {
    return (
        <html lang="en" className={roboto.variable}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <body>
        <Providers>
            <Navbar/>
            {children}
            <Footer/>
        </Providers>
        </body>
        </html>
    );
}
