import "./globals.css";
import Head from "next/head";
import Providers from "./providers";
import { Roboto, Lato, Josefin_Sans } from "@next/font/google";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  variable: "--roboto-font",
});
const lato = Lato({
  weight: ["400", "300", "700"],
  variable: "--lato-font",
});
const josefin = Josefin_Sans({
  weight: "400",
  variable: "--josefin-font",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={roboto.variable}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
